import React, { useState } from 'react';
import { FloatingWindow } from '../windows/WindowManager';
import { useMaterial } from '../material/MaterialProvider';
import { useWorkspacePreferences } from './WorkspacePreferencesProvider';
import { TypographyPreview } from './TypographyPreview';
import { typographyRegistry } from './typographyRegistry';
import { useAudio } from '../audio/AudioProvider';
import { useI18n } from '../i18n/I18nProvider';

const sections = [
  ['appearance', '外观'], ['typography', '字体'], ['background', '背景'],
  ['sound', '声音'], ['time', '时间'], ['language', '语言'],
  ['workspace', '工作区'], ['windows', '窗口'], ['accessibility', '无障碍']
];

function SettingRow({ label, children }) { return <label className="setting-row"><span>{label}</span>{children}</label>; }
function RangeRow({ label, value, min, max, step, onChange, format = item => item }) {
  return <SettingRow label={<>{label}<b>{format(value)}</b></>}><input type="range" min={min} max={max} step={step} value={value} onChange={event => onChange(Number(event.target.value))} /></SettingRow>;
}

export function SettingsWindow({ onClose }) {
  const [active, setActive] = useState('appearance');
  const { state, setSetting, resetSlice, resetAll } = useWorkspacePreferences();
  const { state: materialState, materialOptions, setWorkspaceMaterial, resetMaterial } = useMaterial();
  const { musicActive, toggleAmbientMusic } = useAudio();
  const { t } = useI18n();
  const set = (slice, key) => value => setSetting(slice, key, value);
  const currentSlice = active === 'materials' || active === 'glass' ? 'material' : active;
  const resetCurrent = () => active === 'materials' || active === 'glass' ? resetMaterial() : resetSlice(currentSlice);
  const currentLabel = sections.find(([id]) => id === active)?.[1];

  return <FloatingWindow id="settings" title={t('settings')}>
    <div className="settings-window-body">
      <nav className="settings-nav" aria-label="设置分类">
        {sections.map(([id, label]) => <button type="button" key={id} className={active === id ? 'active' : ''} onClick={() => setActive(id)}>{label}</button>)}
      </nav>
      <section className="settings-content" aria-live="polite">
        <header className="settings-content-header"><div><p className="eyebrow">工作区控制</p><h2>{currentLabel}</h2></div><div><button type="button" className="text-button" onClick={resetCurrent}>重置</button><button type="button" className="text-button muted-button" onClick={resetAll}>全部重置</button><button type="button" className="icon-button" aria-label="关闭设置" onClick={onClose}>×</button></div></header>
        {active === 'appearance' && <><SettingRow label="主题"><select value={state.theme.themeId} onChange={event => set('theme', 'themeId')(event.target.value)}><option value="sakura">樱花 Sakura</option><option value="ember">余烬 Ember</option><option value="moss">苔藓 Moss</option><option value="ink">墨 Ink</option><option value="blush">柔粉</option><option value="pearl">珍珠</option><option value="mist">雾灰</option><option value="night">夜间</option><option value="cobalt">青绿</option></select></SettingRow><SettingRow label="强调色"><input type="color" value={state.theme.accentColor} onChange={event => set('theme', 'accentColor')(event.target.value)} /></SettingRow></>}
        {active === 'materials' && <><SettingRow label="工作区材质"><select value={materialState.workspaceDefault.materialId} onChange={event => setWorkspaceMaterial(event.target.value)}>{materialOptions.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></SettingRow><p className="settings-note">材质参数可在右侧材质预览中继续调整；这里仅切换工作区默认材质。</p></>}
        {active === 'typography' && <><TypographyPreview typography={state.typography} /><SettingRow label="字体"><select value={state.typography.fontFamily} onChange={event => set('typography', 'fontFamily')(event.target.value)}>{typographyRegistry.map(font => <option key={font.id} value={font.id}>{font.name}</option>)}</select></SettingRow><RangeRow label="字体大小" value={state.typography.fontScale} min=".8" max="1.4" step=".05" onChange={set('typography', 'fontScale')} format={value => `${Math.round(value * 100)}%`} /><SettingRow label="字重"><select value={state.typography.fontWeight} onChange={event => set('typography', 'fontWeight')(Number(event.target.value))}><option value="300">细体 300</option><option value="400">常规 400</option><option value="500">中等 500</option><option value="600">半粗 600</option><option value="700">粗体 700</option></select></SettingRow><RangeRow label="字距" value={state.typography.letterSpacing} min="0" max="1.2" step=".1" onChange={set('typography', 'letterSpacing')} format={value => `${value.toFixed(1)}px`} /><RangeRow label="行高" value={state.typography.lineHeight} min="1.2" max="2" step=".05" onChange={set('typography', 'lineHeight')} /></>}
        {active === 'background' && <><SettingRow label="模式"><select value={state.background.mode} onChange={event => set('background', 'mode')(event.target.value)}><option value="color">纯色</option><option value="image">图片</option><option value="gradient">渐变</option></select></SettingRow><SettingRow label="背景颜色"><input type="color" value={state.background.color} onChange={event => set('background', 'color')(event.target.value)} /></SettingRow><SettingRow label="图片地址"><input className="setting-text-input" value={state.background.imageUrl} onChange={event => set('background', 'imageUrl')(event.target.value)} placeholder="https://..." /></SettingRow><SettingRow label="渐变"><input className="setting-text-input" value={state.background.gradient} onChange={event => set('background', 'gradient')(event.target.value)} placeholder="CSS 渐变" /></SettingRow><RangeRow label="模糊" value={state.background.blur} min="0" max="28" step="1" onChange={set('background', 'blur')} format={value => `${value}px`} /><RangeRow label="亮度" value={state.background.brightness} min=".7" max="1.3" step=".05" onChange={set('background', 'brightness')} /><RangeRow label="饱和度" value={state.background.saturation} min=".6" max="1.5" step=".05" onChange={set('background', 'saturation')} /><RangeRow label="不透明度" value={state.background.opacity} min=".2" max="1" step=".05" onChange={set('background', 'opacity')} format={value => `${Math.round(value * 100)}%`} /><RangeRow label="遮罩" value={state.background.overlayOpacity} min="0" max=".6" step=".05" onChange={set('background', 'overlayOpacity')} format={value => `${Math.round(value * 100)}%`} /></>}
        {active === 'glass' && <p className="settings-note">玻璃效果由材质系统管理，请使用右侧材质预览进行实时编辑。</p>}
        {active === 'motion' && <><SettingRow label="启用动效"><input type="checkbox" checked={state.motion.enabled} onChange={event => set('motion', 'enabled')(event.target.checked)} /></SettingRow><SettingRow label="动画级别"><select value={state.motion.animationLevel} onChange={event => set('motion', 'animationLevel')(event.target.value)}><option value="low">低 · 30 秒</option><option value="medium">中 · 21 秒</option><option value="high">高 · 12 秒</option></select></SettingRow><SettingRow label="减少动效"><input type="checkbox" checked={state.motion.reducedMotion} onChange={event => set('motion', 'reducedMotion')(event.target.checked)} /></SettingRow><RangeRow label="持续时间" value={state.motion.durationScale} min=".4" max="1.5" step=".1" onChange={set('motion', 'durationScale')} /></>}
        {active === 'sound' && <><SettingRow label="静音全部声音"><input type="checkbox" checked={state.sound.muted} onChange={event => set('sound', 'muted')(event.target.checked)} /></SettingRow><SettingRow label="界面声音"><input type="checkbox" checked={state.sound.uiSoundEnabled} onChange={event => set('sound', 'uiSoundEnabled')(event.target.checked)} /></SettingRow><RangeRow label="音乐音量" value={state.sound.musicVolume} min="0" max="1" step=".05" onChange={set('sound', 'musicVolume')} format={value => `${Math.round(value * 100)}%`} /><RangeRow label="界面音量" value={state.sound.uiVolume} min="0" max="1" step=".05" onChange={set('sound', 'uiVolume')} format={value => `${Math.round(value * 100)}%`} /><SettingRow label="环境音乐"><button type="button" className="select-model sound-toggle" disabled={state.sound.muted || state.sound.musicVolume === 0} onClick={() => { toggleAmbientMusic(); set('sound', 'musicEnabled')(!musicActive); }}>{musicActive ? '停止' : '开始'}</button></SettingRow><p className="settings-note">环境音乐在本地生成，只有点击开始后才会播放。</p></>}
        {active === 'time' && <><SettingRow label={t('clockFormat')}><select value={state.time.clockFormat} onChange={event => set('time', 'clockFormat')(event.target.value)}><option value="24h">{t('twentyFourHour')}</option><option value="12h">{t('twelveHour')}</option></select></SettingRow><SettingRow label={t('showSeconds')}><input type="checkbox" checked={state.time.showSeconds} onChange={event => set('time', 'showSeconds')(event.target.checked)} /></SettingRow><SettingRow label={t('showDate')}><input type="checkbox" checked={state.time.showDate} onChange={event => set('time', 'showDate')(event.target.checked)} /></SettingRow><SettingRow label={t('timezone')}><select value={state.time.timezoneMode} onChange={event => set('time', 'timezoneMode')(event.target.value)}><option value="system">{t('systemTimezone')}</option><option value="custom">{t('customTimezone')}</option></select></SettingRow>{state.time.timezoneMode === 'custom' && <SettingRow label="IANA 时区"><input className="setting-text-input" value={state.time.timezone || ''} onChange={event => set('time', 'timezone')(event.target.value)} placeholder="Asia/Shanghai" /></SettingRow>}</>}
        {active === 'language' && <><SettingRow label={t('locale')}><select value={state.language.locale} onChange={event => set('language', 'locale')(event.target.value)}><option value="zh-CN">{t('chinese')}</option><option value="en">{t('english')}</option><option value="system">{t('followSystem')}</option></select></SettingRow><p className="settings-note">语言变更会立即更新已注册的界面文本、日期和时间。</p></>}
        {active === 'workspace' && <><SettingRow label="吸附窗口"><input type="checkbox" checked={state.workspace.snapEnabled} onChange={event => set('workspace', 'snapEnabled')(event.target.checked)} /></SettingRow><SettingRow label="显示停靠栏"><input type="checkbox" checked={state.workspace.dockVisible} onChange={event => set('workspace', 'dockVisible')(event.target.checked)} /></SettingRow></>}
        {active === 'windows' && <p className="settings-note">窗口布局、位置、尺寸和层级由窗口管理器管理，并单独持久化。</p>}
        {active === 'accessibility' && <><SettingRow label="高对比度"><input type="checkbox" checked={state.accessibility.highContrast} onChange={event => set('accessibility', 'highContrast')(event.target.checked)} /></SettingRow><SettingRow label="大号文字"><input type="checkbox" checked={state.accessibility.largeText} onChange={event => set('accessibility', 'largeText')(event.target.checked)} /></SettingRow><SettingRow label="显示焦点"><input type="checkbox" checked={state.accessibility.focusVisible} onChange={event => set('accessibility', 'focusVisible')(event.target.checked)} /></SettingRow></>}
      </section>
    </div>
  </FloatingWindow>;
}
